name: "sdl"
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: libsdl-org/setup-sdl@main
        id: sdl
        with:
          version: 3-head
          version-sdl-image: 3-head
          version-sdl-ttf: 3-head
          
      - name: 'Configure and build your project'
        run: |
          cmake -G"Ninja" -S . -B build
          cmake --build build --verbose
